# Generated by Django 4.1.5 on 2023-05-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/ProfilePic.jpg', upload_to='profile_pics/'),
        ),
    ]
