# Generated by Django 4.1.5 on 2023-06-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_profile_friends_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
