# Generated by Django 4.1.5 on 2023-06-20 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_profile_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
